name: Daily Refresh

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python update_data.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/portfolio.json
          git commit -m "Auto-update dashboard (daily)" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push origin main --force-with-lease
        