name: Update ESG Automation Backtest

on:
  schedule:
    - cron: "0 0 * * *"   # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write      # Allow workflow to push changes

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy matplotlib openpyxl

      # 4. Run backtest with UTF-8 encoding
      - name: Run backtest
        run: |
          export PYTHONIOENCODING=utf-8
          python main.py

      # 5. Commit and push changes to docs/
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs
          git commit -m "Auto-update dashboard (daily)" || echo "No changes to commit"
          git push
