name: Update ESG Automation Backtest

on:
  schedule:
    - cron: "0 0 * * 0"   # Weekly run (Sunday)
  workflow_dispatch:      # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false   # Important for later push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy matplotlib

      - name: Run backtest and generate docs
        run: python main.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs
          git commit -m "Auto-update backtest results" || echo "No changes to commit"
          git push
