name: Update ESG Automation Backtest

on:
  schedule:
    - cron: "0 0 * * 0"   # Weekly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # allow pushing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy matplotlib openpyxl

      - name: Run backtest
        run: python main.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs
          git commit -m "Auto-update backtest results" || echo "No changes"
          git push
